export const translations = {
  en: {
    appTitle: "Saarthi AI",
    tagline: "• Legal • Banking • Medical",
    newChat: "New Chat",
    documents: "Documents",
    systemStats: "System stats",
    activeThread: "Active Thread:",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    older: "Older",
    welcomeTitle: "Saarthi AI",
    welcomeSubtitle: "• Legal • Banking • Medical",
    inputPlaceholder: "Ask about your uploaded document, or ask about legal, banking & medical topics...",
    listening: "Listening...",
    transcribing: "Transcribing voice input...",
    stopBtn: "Stop generation",
    addAttachment: "Add attachment",
    uploadDoc: "Upload Document (PDF, DOCX)",
    takePhoto: "Take Photo",
    uploadPhoto: "Upload Photo",
    recordVoice: "Record voice input",
    stopRecord: "Stop recording",
    noDocs: "No documents uploaded yet.",
    avgLatency: "Avg Latency",
    throughput: "Throughput",
    totalQueries: "Total Queries",
    withContext: "With Context",
    recentQueries: "Recent Queries (Last 20)",
    qTime: "Time",
    qPreview: "Query Preview",
    qLang: "Lang",
    qChunks: "Chunks",
    qTokens: "Tokens",
    qTps: "t/s",
    qStatus: "Status",
    qSkipped: "Skipped",
    qAnswered: "Answered",
    noTelemetry: "No query stats logged.",
    sourceTitle: "Source Citation",
    metadata: "Metadata",
    fileName: "File Name",
    pageNumber: "Page Number",
    category: "Category / Domain",
    sourceOrigin: "Source Origin",
    userDoc: "User Document",
    publicKb: "Public Knowledge Base",
    docExcerpt: "Document Excerpt",
    docPrivate: "Content not displayed for privacy",
    sourcesList: "Sources",
    sourcesToggle: "Sources",
    listenBtn: "Listen to answer",
    stopListen: "Stop speaking",
    copyBtn: "Copy to clipboard",
    confirmDelete: "Delete document? This will remove it from your session.",
    confirm: "Confirm",
    cancel: "Cancel",
    
    // Phase 0 additions
    offlineMode: "Offline Mode Active",
    welcomeHeading: "How can I help you today?",
    searchPlaceholder: "Search conversations, messages, or documents...",
    searchConversations: "Conversations",
    searchMessages: "Messages",
    searchDocuments: "Documents",
    noResults: "No results found.",
    verified: "Verified",
    notFound: "Not found",
    noSources: "No sources",
    deleteConversation: "Delete",
    renameConversation: "Rename",
    confirmDeleteConversation: "Are you sure you want to delete this conversation? This will also delete all associated uploaded document vectors.",
    editMessage: "Edit message",
    deleteMessage: "Delete message",
    regenerate: "Regenerate",
    continueGeneration: "Continue",
    retry: "Retry",
    copyMarkdown: "Copy Markdown",
    copyPlainText: "Copy Plain Text",
    exportResponse: "Export to Markdown",
    feedbackThanks: "Thank you for your feedback!",
    thumbsUp: "Helpful",
    thumbsDown: "Not helpful",
    uploadTimeline_uploading: "Uploading...",
    uploadTimeline_ocr: "OCR Processing...",
    uploadTimeline_embedding: "Embedding...",
    uploadTimeline_indexing: "Indexing...",
    uploadTimeline_ready: "Ready",
    cameraTitle: "Camera Capture",
    capture: "Capture",
    retake: "Retake",
    crop: "Crop",
    rotate: "Rotate",
    noCameraDetected: "No camera detected. Please upload a photo instead.",
    recentUploads: "Recent Uploads in this Chat",
    dropFileHere: "Drop files here to upload",
    pasteImage: "Image pasted",
    llmReady: "LLM Ready",
    llmOffline: "LLM Offline",
    kbChunks: "KB Chunks",
    embeddingModel: "Embed Model",
    documentsCount: "Docs Count",
    messageCount: "Messages",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemLabel: "System",
    renamePlaceholder: "Enter new title...",
    documentsHeader: "Documents Manager",
    confirmRename: "Save",
    reindex: "Re-index",
    statusIndexed: "Indexed",
    statusFailed: "Failed",
    statusPending: "Pending"
  },
  hi: {
    appTitle: "सारथी एआई",
    tagline: "• कानूनी • बैंकिंग • चिकित्सा",
    newChat: "नया चैट",
    documents: "दस्तावेज़",
    systemStats: "सिस्टम आँकड़े",
    activeThread: "सक्रिय थ्रेड:",
    today: "आज",
    yesterday: "कल",
    thisWeek: "इस सप्ताह",
    older: "पुराना",
    welcomeTitle: "सारथी एआई",
    welcomeSubtitle: "• कानूनी • बैंकिंग • चिकित्सा",
    inputPlaceholder: "अपने अपलोड किए गए दस्तावेज़ के बारे में पूछें, या कानूनी, बैंकिंग और चिकित्सा विषयों के बारे में पूछें...",
    listening: "सुन रहा हूँ...",
    transcribing: "आवाज इनपुट ट्रांसक्राइब हो रहा है...",
    stopBtn: "जनरेशन रोकें",
    addAttachment: "अटैचमेंट जोड़ें",
    uploadDoc: "दस्तावेज़ अपलोड करें (PDF, DOCX)",
    takePhoto: "फोटो लें",
    uploadPhoto: "फोटो अपलोड करें",
    recordVoice: "आवाज रिकॉर्ड करें",
    stopRecord: "रिकॉर्डिंग रोकें",
    noDocs: "अभी तक कोई दस्तावेज़ अपलोड नहीं किया गया है।",
    avgLatency: "औसत विलंबता",
    throughput: "थ्रूपुट",
    totalQueries: "कुल प्रश्न",
    withContext: "संदर्भ के साथ",
    recentQueries: "हाल के प्रश्न (अंतिम 20)",
    qTime: "समय",
    qPreview: "प्रश्न पूर्वावलोकन",
    qLang: "भाषा",
    qChunks: "चंक",
    qTokens: "टोकन",
    qTps: "t/s",
    qStatus: "स्थिति",
    qSkipped: "छोड़ा गया",
    qAnswered: "उत्तर दिया",
    noTelemetry: "कोई लॉग उपलब्ध नहीं है।",
    sourceTitle: "स्रोत संदर्भ",
    metadata: "मेटाडेटा",
    fileName: "फ़ाइल का नाम",
    pageNumber: "पृष्ठ संख्या",
    category: "श्रेणी / डोमेन",
    sourceOrigin: "स्रोत का प्रकार",
    userDoc: "उपयोगकर्ता दस्तावेज़",
    publicKb: "सार्वजनिक ज्ञानकोश",
    docExcerpt: "दस्तावेज़ का अंश",
    docPrivate: "गोपनीयता के लिए सामग्री प्रदर्शित नहीं की गई है",
    sourcesList: "स्रोत",
    sourcesToggle: "स्रोत",
    listenBtn: "उत्तर सुनें",
    stopListen: "बोलना बंद करें",
    copyBtn: "क्लिपबोर्ड पर कॉपी करें",
    confirmDelete: "दस्तावेज़ हटाना चाहते हैं? यह आपके सत्र से हट जाएगा।",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    
    // Phase 0 additions
    offlineMode: "ऑफलाइन मोड सक्रिय",
    welcomeHeading: "मैं आज आपकी क्या सहायता कर सकता हूँ?",
    searchPlaceholder: "चैट, संदेश या दस्तावेज़ खोजें...",
    searchConversations: "चैट",
    searchMessages: "संदेश",
    searchDocuments: "दस्तावेज़",
    noResults: "कोई परिणाम नहीं मिला।",
    verified: "सत्यापित",
    notFound: "नहीं मिला",
    noSources: "कोई स्रोत नहीं",
    deleteConversation: "हटाएं",
    renameConversation: "नाम बदलें",
    confirmDeleteConversation: "क्या आप वाकई इस चैट को हटाना चाहते हैं? इससे सभी संबंधित दस्तावेज़ भी हट जाएंगे।",
    editMessage: "संदेश संपादित करें",
    deleteMessage: "संदेश हटाएं",
    regenerate: "पुनः उत्पन्न करें",
    continueGeneration: "जारी रखें",
    retry: "पुनः प्रयास करें",
    copyMarkdown: "मार्कडाउन कॉपी करें",
    copyPlainText: "सामान्य पाठ कॉपी करें",
    exportResponse: "मार्कडाउन निर्यात करें",
    feedbackThanks: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    thumbsUp: "मददगार",
    thumbsDown: "मददगार नहीं",
    uploadTimeline_uploading: "अपलोड हो रहा है...",
    uploadTimeline_ocr: "ओसीआर प्रक्रिया...",
    uploadTimeline_embedding: "एम्बेडिंग...",
    uploadTimeline_indexing: "इंडेक्सिंग...",
    uploadTimeline_ready: "तैयार",
    cameraTitle: "कैमरा कैप्चर",
    capture: "खिंचे",
    retake: "फिर लें",
    crop: "काटें",
    rotate: "घुमाएं",
    noCameraDetected: "कैमरा नहीं मिला। कृपया फोटो अपलोड करें।",
    recentUploads: "इस चैट में हाल के अपलोड",
    dropFileHere: "अपलोड करने के लिए फाइलें यहाँ छोड़ें",
    pasteImage: "छवि पेस्ट की गई",
    llmReady: "एआई तैयार",
    llmOffline: "एआई ऑफलाइन",
    kbChunks: "केबी चंक्स",
    embeddingModel: "मॉडल",
    documentsCount: "दस्तावेज़ संख्या",
    messageCount: "संदेश",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemLabel: "सिस्टम",
    renamePlaceholder: "नया नाम दर्ज करें...",
    documentsHeader: "दस्तावेज़ प्रबंधक",
    confirmRename: "सहेजें",
    reindex: "पुनः इंडेक्स",
    statusIndexed: "सत्यापित",
    statusFailed: "विफल",
    statusPending: "प्रतीक्षारत"
  }
};
